#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli@latest
  - npm install -g firebase-tools
  - npm install --save @angular/material
  - npm install --save @angular/animations
  - npm install --save hammerjs

script:
  - ng build --prod --aot
  - npm run precache

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change